on:
  workflow_call:
    inputs:
      php:
        description: PHP version
        type: string
        required: false
        default: 8.1
    secrets:
      stryker-api-key:
        required: false

jobs:
  infection:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.php }}
          ini-file: development
          tools: composer:v2
      - uses: ramsey/composer-install@v3
        with:
          composer-options: --optimize-autoloader
      - run: composer infection
        env:
          STRYKER_DASHBOARD_API_KEY: ${{ secrets.stryker-api-key }}
