on:
  workflow_call:
    secrets:
      pat:
        required: true

jobs:
  sync-repo-description:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: composer.json
      - uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.pat }}
          script: |
            const composer = require('./composer.json');
            await github.rest.repos.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              description: composer.description,
            });
            await github.rest.repos.replaceAllTopics({
              owner: context.repo.owner,
              repo: context.repo.repo,
              names: composer.keywords.map((keyword) => keyword.toLowerCase()),
            });
